issue #3 Add multilingual support
fujitsu-pio/wakaba-user-app pull request #4
Opened 2017-08-22 02:44 UTC by csKyou

2017-08-22 06:47 UTC, dixonsiu requested changes

2017-08-22 06:47 UTC, dixonsiu commented on src/LLMessage.html
> +        <h1 data-i18n="llmessage:header"></h1>
Please avoid using generic naming here.

Suggestion: llmessage:wakabaCity

2017-08-22 06:47 UTC, dixonsiu commented on src/LLMessage.html
> +    <section class="login-section">
1. Delete the class attribute if not needed, OR,
2. Rename the class and the corresponding CSS style

2017-08-22 06:47 UTC, dixonsiu commented on src/js/common.js
> +Common.AddResourceProfile = function(lng , ns, id, json) {
This implementation only works now, it will not work properly if lng is not "en" or "ja". Therefore, it is better to use only line 35 and 41 for now. Besides, profile.json does not support multi-languages currently.

2017-08-22 06:47 UTC, dixonsiu commented on src/js/LLMessage.js
> +                        var targetName = "llmessage:approved" + i;
Remove i18next and just simply display  prof[0].DisplayName + prof[0].Description.

2017-08-22 06:47 UTC, dixonsiu commented on src/js/LLMessage.js
> +                //if (lm.isExpired(messageBody.TermEnd)) {
Delete it if you think you don't need this feature in the near future. OR,
Implement it as an option.
old:

    if (lm.isExpired(messageBody.TermEnd)) {

suggested:

    lm.showExpiredMessage = true;
    ...
    if (lm.showExpiredMessage || lm.isExpired(messageBody.TermEnd)) {

2017-08-22 06:47 UTC, dixonsiu commented on src/js/LLMessage.js
> +                $('#requestName').html('<div class="sizeCaption" data-i18n="llmessage:msg' + i + '_DisplayName"></div>').localize();
Revert back to single language

2017-08-22 06:47 UTC, dixonsiu commented on src/js/LLMessage.js
> + */
Comments: If the retrieved message's timestamp is not today, it is considered expired.

[Timestamp issue](https://github.com/personium/personium-core/issues/42)

2017-08-22 10:15 UTC, csKyou commented on src/js/LLMessage.js
> + */
It has changed.

2017-08-22 10:16 UTC, csKyou commented on src/js/common.js
> +Common.AddResourceProfile = function(lng , ns, id, json) {
Fix to use the result of profile.json as it is.

2017-08-22 10:17 UTC, csKyou commented on src/LLMessage.html
> +        <h1 data-i18n="llmessage:header"></h1>
Changed the sentence to a predictable name.

2017-08-23 04:18 UTC, csKyou commented on src/LLMessage.html
> +        <h1 data-i18n="llmessage:header"></h1>
Changed the sentence to a predictable name.

2017-08-23 04:19 UTC, csKyou commented on src/LLMessage.html
> +    <section class="login-section">
Deleted the class attribute.

2017-08-23 04:19 UTC, csKyou commented on src/js/common.js
> +Common.AddResourceProfile = function(lng , ns, id, json) {
Deleted the processing of i18n and restored it to use the profile as it is.

2017-08-23 04:19 UTC, csKyou commented on src/js/LLMessage.js
> +                        var targetName = "llmessage:approved" + i;
Deleted the processing of i18n and restored it to use the profile as it is.

2017-08-23 04:20 UTC, csKyou commented on src/js/LLMessage.js
> +                //if (lm.isExpired(messageBody.TermEnd)) {
It was implemented as an option.

2017-08-23 04:20 UTC, csKyou commented on src/js/LLMessage.js
> +                $('#requestName').html('<div class="sizeCaption" data-i18n="llmessage:msg' + i + '_DisplayName"></div>').localize();
Deleted the processing of i18n and restored it to use the profile as it is.

2017-08-23 04:20 UTC, csKyou commented on src/js/LLMessage.js
> + */
It has changed.

2017-08-23 05:03 UTC, dixonsiu approved these changes

2017-08-23 05:04 UTC, merged